### ISSUE TITLE
Panic errors from empty arguments

### ISSUE THREAD

**Issue by ozerovandrei** [serboox/os-cli#1]
Hello.

I've tried to use this project for a while.

For some reason I'm getting runtime errors when I try to run the cli commands without any arguments.

Show command:
```
root@6790fe0e751d:/go/src/github.com/serboox/os-cli# ./os-cli show
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x66199b]

goroutine 1 [running]:
github.com/serboox/os-cli/models.(*ResAuthTokens).Post(0xc42007ce60, 0x958820, 0xc4200516d8, 0x6c05e6, 0xc42008661c)
	/go/src/github.com/serboox/os-cli/models/tokens.go:143 +0x49b
github.com/serboox/os-cli/controllers.ShowInstances(0x958820, 0xc420051740, 0x6c3b61)
	/go/src/github.com/serboox/os-cli/controllers/show.go:16 +0x51
github.com/serboox/os-cli/cmd.ShowInstances.func1(0xc4200d0dc0, 0x0, 0xc4200d0dc0)
	/go/src/github.com/serboox/os-cli/cmd/show.go:20 +0x2a
github.com/serboox/os-cli/vendor/github.com/urfave/cli.HandleAction(0x70cf20, 0xc42007acf0, 0xc4200d0dc0, 0xc420116300, 0x0)
	/go/src/github.com/serboox/os-cli/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/serboox/os-cli/vendor/github.com/urfave/cli.Command.Run(0x77d064, 0x4, 0x0, 0x0, 0xc42007ad00, 0x1, 0x1, 0x77f7e6, 0xe, 0x0, ...)
	/go/src/github.com/serboox/os-cli/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/serboox/os-cli/vendor/github.com/urfave/cli.(*App).Run(0xc4200a29c0, 0xc42008e000, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/serboox/os-cli/vendor/github.com/urfave/cli/app.go:255 +0x6a0
main.main()
	/go/src/github.com/serboox/os-cli/os-cli.go:29 +0x282
```

Create command:
```
root@6790fe0e751d:/go/src/github.com/serboox/os-cli# ./os-cli create
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x66199b]

goroutine 1 [running]:
github.com/serboox/os-cli/models.(*ResAuthTokens).Post(0xc42007cd20, 0x958820, 0xc420051710, 0xc4200810a8, 0xc420081040)
	/go/src/github.com/serboox/os-cli/models/tokens.go:143 +0x49b
github.com/serboox/os-cli/controllers.CreateInstance(0x958820, 0xc420051740, 0x6c3b61)
	/go/src/github.com/serboox/os-cli/controllers/create.go:17 +0x62
github.com/serboox/os-cli/cmd.CreateInstance.func1(0xc4200d0b00, 0x0, 0xc4200d0b00)
	/go/src/github.com/serboox/os-cli/cmd/create.go:20 +0x2a
github.com/serboox/os-cli/vendor/github.com/urfave/cli.HandleAction(0x70cf20, 0xc42007acd0, 0xc4200d0b00, 0xc420116300, 0x0)
	/go/src/github.com/serboox/os-cli/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/serboox/os-cli/vendor/github.com/urfave/cli.Command.Run(0x77d582, 0x6, 0x0, 0x0, 0xc42007ace0, 0x1, 0x1, 0x77fb5c, 0xf, 0x0, ...)
	/go/src/github.com/serboox/os-cli/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/serboox/os-cli/vendor/github.com/urfave/cli.(*App).Run(0xc4200a29c0, 0xc42008e000, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/serboox/os-cli/vendor/github.com/urfave/cli/app.go:255 +0x6a0
main.main()
	/go/src/github.com/serboox/os-cli/os-cli.go:29 +0x282
```

**Comment by serboox** [comment]
Yes you are right, I forgot add validation methods in my `cmd` package.
